from .start import router
from .profile import router
from .habits import router
from .rating import router
from .achievements import router
from .friends import router
from .skills import router
from .pvp import router
from .settings import router